!obj:pylearn2.train.Train {
    save_path: '/home/chong/workspace/kaggle/kaggle-mnist/CNN/cnn_train.pkl',
    save_freq: 1,
    dataset: &train !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix {
        X: !pkl: 'data/mnist_train_X.pkl',
        y: !pkl: 'data/mnist_train_y.pkl',
        y_labels: 10,
    },
    model: !obj:cnn.CNN {
        nvis: 784,
        nhid: 200,
        nclasses: 10,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 200,
        learning_rate: 1e-3,
        monitoring_dataset: {
            'train' : *train,
            'valid' : !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix {
                X: !pkl: 'data/mnist_valid_X.pkl',
                y: !pkl: 'data/mnist_valid_y.pkl',
                y_labels: 10,
            },
            'test' : !obj:pylearn2.datasets.dense_design_matrix.DenseDesignMatrix {
                X: !pkl: 'data/mnist_test_X.pkl',
                y: !pkl: 'data/mnist_test_y.pkl',
                y_labels: 10,
            },
        },
        cost: !obj:cnn.CNNCost {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 1500
        },
    },
}